# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 04:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 16, 4, 46, 36, 490222, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
